steinbergmedia/vstgui

vstgui/plugin-bindings/vst3editor.cpp
This is necessary when you change the tag of a control.
=> Also call setMin and setMax on control as this can change after CControl::setTag was called

vstgui/lib/platform/mac/macfileselector.mm
While 10.11 wasn’t crashing, older systems (e.g. 10.9.5) were and
without the retain, "uti" would get released a few lines below, causing
a crash every time the Open or Save dialogs were used.
=> Fix crash on CNewFileSelector (macfileselector.mm) because of a missing retain.

vstgui/lib/platform/mac/macclipboard.mm
The method is available since Mac OS X 10.6 and more precisely represents intention of the code.
=> Clear NSPasteboard contents if dataSource is not valid.

vstgui/lib/platform/mac/cocoa/nsviewoptionmenu.mm
Use of getCurrentIndex() instead of getValue() is consistent with OS X Carbon and Windows.
=> Fix Cocoa check style COptionMenu which displayed check mark next to wrong menu item

vstgui/lib/platform/win32/win32frame.cpp, vstgui/lib/platform/win32/win32support.cpp, vstgui/lib/platform/win32/win32support.h, vstgui/lib/platform/win32/win32textedit.cpp, vstgui/lib/platform/win32/winfileselector.cpp
WINAPI_FAMILY_SYSTEM is defined in Windows 10 SDK. For other SDKs behavior is like before.
Occurences of:
getSystemVersion ().dwMajorVersion >= 6
Need to be replaced with:
IsWindowsVistaOrGreater()
Tested with Windows SDK Versions 10.0.10586.0 and 8.1. Tested build of uidescription test_vs2015.
=> FIXED Windows 10 SDK build.

vstgui/plugin-bindings/vst3editor.cpp
Found with Address Sanitizer on Linux. But it affects all platforms.
=> Fix memory leak by using shared pointer

vstgui/plugin-bindings/aeffguieditor.cpp
There is a missing inclusion in *AEffGuiEditor* causing the compilation to fail because of *IPlatformFrame* being an incomplete type.
=> resolve incomplete type IPlatformFrame in VST2 binding

vstgui/lib/platform/mac/carbon/hiviewframe.cpp
dynamic_cast fails because the source is of type PlatformBitmapPtr, a SharedPointer. Instead, use SharedPointer.cast.
=> fix a compilation error in Carbon sources

vstgui/lib/cviewcontainer.cpp
If there is a view in the children container with only one reference left, erasing it from the list will call its destructor. However, it will be deferenced in the following code.
The change postpones CView deletion up to the end of the while loop body.
=> Avoid dereferencing a deleted CView in CViewContainer::removeAll

vstgui/lib/cstring.h
On 32bit systems there's no need to cast string length to 64bit
=> Fix unnecessary 32-to-64-bit conversion and precision loss warning

vstgui/lib/platform/win32/win32frame.cpp, vstgui/lib/platform/win32/win32frame.h
-Retrieve modifier keys asynchronously, so e.g. Pro Tools doesn't steal them away.
-Forward unprocessed key events to the previous focus window so we don't steal them away from e.g. Pro Tools.
=> Patch for win32 keyboard focus issues

vstgui/plugin-bindings/vst3editor.cpp
Check the runLoop pointer which is used. The latest Reaper (https://aur.archlinux.org/packages/reaper/) crashes to desktop otherwise because the runLoop pointer is null. By checking the pointers the GUI is still black but "better" than crashing.
=> Check runLoop pointer before using it.

vstgui/uidescription/CMakeLists.txt
The module is "FindEXPAT.cmake" (so all caps in `find_package()` expected) according to https://cmake.org/cmake/help/v3.11/module/FindEXPAT.html.
=> Fix Expat naming in `find_package()` command

vstgui/lib/cdrawcontext.cpp, vstgui/lib/cdrawcontext.h, vstgui/lib/cframe.cpp, vstgui/lib/cframe.h, vstgui/lib/platform/mac/cgdrawcontext.cpp, vstgui/lib/platform/mac/cgdrawcontext.h, vstgui/lib/platform/win32/direct2d/d2ddrawcontext.cpp, vstgui/lib/vstguifwd.h
The bitmap scaling quality can be set per CDrawContext instance using the CDrawContext::setBitmapInterpolationQuality() or globally per CFrame instance using CFrame::setBitmapInterpolationQuality(), which then delegates the setting to the respective draw context in CFrame::drawRect().
Currently, there are three modes: kQualityDefault, kQualityLow, kQualityMedium and kQualityHigh.
This feature is transparent, i.e. nothing will change from the current behavior unless you set anything != kQualityDefault.
NOTE: A Gdiplus back end implementation was skipped given that Gdiplus will deprecated soon. Linux support is missing due to the lack of a test setup. Since the older direct2d API which d2ddrawcontext is based on only offers two modes (nearest neighbour and bilinear), the kQualityMedium and …
=> Add support for different bitmap scaling qualities (BitmapInterpolationQuality)

vstgui/plugin-bindings/plugguieditor.cpp, vstgui/plugin-bindings/plugguieditor.h
Remove getFrame() function override - the same function is defined
as const in parent class VSTGUIEditorInterface.
This removes the last occurrence of USE_NAMESPACE macro in VSTGUI.
Remove unused private member inIdleStuff.
=> fix plugguieditor warnings

vstgui/lib/cframe.cpp
Issue: The GenericOptionMenu does not accept any mouse wheel when the editor is scaled (scaleFactor != 1). Therefore it is impossible to scroll inside the menu.
Solution: Whenever the CFrame passes on a <tt>CPoint where</tt> to the modal view it is "inverse transformed" to <tt>where2</tt> beforehand. Examples are <tt>CFrame::onMouseMoved</tt>, <tt>CFrame::onMouseDown</tt>, <tt>CFrame::hitTestSubViews</tt> ...
Therefore I believe it must be done in <tt>CFrame::onWheel</tt> as well.
=> Inverse transform position before passing it on.

vstgui/vstgui_linux.cpp, vstgui/vstgui_mac.mm
Since lib/platform/common/fileresourceinputstream.cpp is already being
included by vstgui.cpp, it does not need to be included by
vstgui_linux.cpp or vstgui_mac.mm.
=> Do not include fileresourceinputstream.cpp twice

vstgui/lib/platform/linux/x11frame.cpp
I discussed that [issue](https://github.com/steinbergmedia/vstgui/issues/80) with @abique. Obviously he was facing a quite similar problem a while back.
Using ref-counting seems to solve the issue.
=> Fix crash when close/reopen editor several times.

vstgui/lib/platform/win32/win32optionmenu.cpp
Menu items with submenus beneath them dont accurately support
checkmarks on windows. This patch restores them. Thank you for considering this
patch!
Thanks to @sagantech who identified it.
=> Enable checkmarks on Parent Menus in Win32

vstgui/lib/platform/common/genericoptionmenu.cpp
GenericOptionMenu (only used in linux) didn't respond to enter
in either master or develop branch. This change makes enter and
return both send the click callback if the callback is registered,
making keyboard navigation of the menus rather nice.
=> Enter in GenericMenu

vstgui/lib/cscrollview.cpp
CScrollView::removeAll ignores withForget parameter
=> [bug] CScrollView::removeAll ignores withForget parameter

vstgui/lib/platform/linux/x11frame.h
The method has two definitions in conflict, one being in the header and the other found in `x11frame.cpp`.
=> Fix a build error in X11::Frame

vstgui/lib/cframe.cpp, vstgui/plugin-bindings/vst3editor.cpp
This fixes an issue causing VST3 plug-ins on Windows to not respond correctly to non-integer scale factors (e.g. 175%) and therefore be scaled incorrectly in hosts.
=> Fix rounding error when using a non-integer scale factor

vstgui/lib/crect.h
Hi, this fixes a gcc warning, which can be very intrusive sometimes.
When the copy ctor is user-defined, the compiler complains about the assignment operator which isn't
=> Fix a gcc warning -Wdeprecated-copy

vstgui/lib/controls/csegmentbutton.cpp, vstgui/tests/unittest/lib/controls/csegmentbutton_test.cpp
When a segment button has e.g. 32 entries, it is not possible to click on some segments because of rounding errors. Therefore proper rounding is needed.
=> Round segmentIndex properly.

vstgui/tests/unittest/uidescription/uiattributes_test.cpp, vstgui/uidescription/uiattributes.cpp
This fixes a crash, when leaving the segment-names (Segment Button) empty in the Live Editor.
=> Return an empty string, when string list is empty

vstgui/lib/vstguifwd.h
Currently failing with `std::numeric_limits` not found.
=> Fix the build with gcc 11

vstgui/lib/platform/linux/cairocontext.cpp, vstgui/lib/platform/linux/cairocontext.h
The correctly transformed clip rect is already in the current state. Applying the current transform may add other transforms that were set after the clip was set.
=> fix wrong clip rect calculation on linux

vstgui/lib/platform/linux/x11frame.cpp
If you have two CFrames open (for example two instances of the same
plugin), and close one of them, the drawing in the other one starts to
fail, with "the target surface has been finished" messages. The fix is
simple: just remove the call to cairo_device_finish.
cairo_device_destroy will call cairo_device_finish when it has decreased
the refcount to zero.
=> fix cairo drawing error when another frame closes

vstgui/lib/cfont.cpp, vstgui/lib/cfont.h, vstgui/lib/vstguiinit.cpp
global fonts are now initialized in VSTGUI::init() and cleaned up in VSTGUI::exit() to prevent leaks and using dangled pointers
=> init and terminate global fonts in a predicated way

vstgui/lib/cview.cpp, vstgui/lib/cview.h, vstgui/lib/iviewlistener.h, vstgui/lib/platform/common/genericoptionmenu.cpp, vstgui/lib/platform/common/genericoptionmenu.h, vstgui/lib/vstguifwd.h, vstgui/tests/unittest/lib/cview_test.cpp, vstgui/uidescription/editing/uieditcontroller.cpp
as view events are dispatched very often it is more efficient to decouple this from the generic view listener interface
=> make extra interface for view event listening

vstgui/plugin-bindings/vst3editor.cpp, vstgui/plugin-bindings/vst3editor.h
Make vst3editor usable again, following the `IMouseObserver` changes.
=> Update vst3editor to the new mouse hook interface

vstgui/vstgui_linux.cpp
This lacks a source file, making the unity build fail on Linux platform.
=> Add missing source to vstgui_linux.cpp

vstgui/lib/platform/linux/x11frame.cpp, vstgui/lib/platform/linux/x11platform.cpp, vstgui/lib/platform/linux/x11platform.h
cairo_device_finish must be called before closing the xcb connection,
otherwise the invalid connection will not be removed from an internal
cairo cache. When reopening the editor there's then a risk that the
new connection has the same pointer value as the old one and that will
cause a crash.
The call to cairo_device_finish should not be made until the last
instance of the editor has been closed. If it's done earlier, the
remaining editors will stop working.
=> fix close/reopen crash on linux. Fixes #249.

vstgui/plugin-bindings/vst3editor.cpp
No need to subtract 'minValue' in this case. All transforms of value from physical to normalized and vice versa is handled correctly by CControl already. When 'minValue' > 0 it even breaks the segment button.
=> Remove substraction of minValue.

vstgui/lib/algorithm.h
While building VST3SDK, I got this error on VSTGUI:
```
[ 60%] Building CXX object VSTGUI.build/standalone/CMakeFiles/vstgui_standalone.dir/source/uidescriptionwindowcontroller.cpp.o
In file included from /home/carlo/packages/vst3sdk/vst3sdk/vstgui4/vstgui/standalone/source/uidescriptionwindowcontroller.cpp:5:
/home/carlo/packages/vst3sdk/vst3sdk/vstgui4/vstgui/standalone/source/../../lib/algorithm.h:15:63: error: ‘int32_t’ does not name a type
15 | template <typename Iter, typename Type, typename ResultType = int32_t>
|                                                               ^~~~~~~
/home/carlo/packages/vst3sdk/vst3sdk/vstgui4/vstgui/standalone/source/../../lib/algorithm.h:9:1: note: ‘int32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
8 | #include …
```
=> Fix build error on missing cstdint types.

vstgui/lib/platform/mac/mactimer.cpp
`MAX_OS_X_VERSION_10_8` is not a macro defined by Apple's headers; it should be `MAC_OS_X_VERSION_10_8`.
It's a good idea to use the [`-Wundef`](https://clang.llvm.org/docs/DiagnosticsReference.html#wundef) compiler flag to catch these kinds of issues.
=> Fix build warning in mactimer.cpp

vstgui/lib/platform/win32/winfileselector.cpp
Unlike the macOS implementation, `CNewFileSelector` on Windows does not invoke the `CallbackFunc` or emit the `kSelectEndMessage` notification if the user cancels the file selector.
This seems to be a bug based on the existence of a [commit that fixed it in an earlier version of the implementation](https://github.com/steinbergmedia/vstgui/commit/7cdf23962f513ead054cfdd4b00c0df923ebd779).
This pull requests ensures that the `doneCallback` is executed on all code paths, so that clients of `CNewFileSelector` can reliably perform any necessary clean-up.
=> Notify callback or delegate when VistaFileSelector is canceled

vstgui/lib/cfileselector.cpp
`CNewFileSelector` objects were being leaked when using `run (CallbackFunc&&)` because of a retain cycle; the lambda assigned to `impl->doneCallback` added a `SharedPointer` to `this` that would never be freed.
Verified by adding a breakpoint on `CNewFileSelector::~CNewFileSelector()`
=> Fix leak in CNewFileSelector::run (CallbackFunc&& callback)

vstgui/lib/platform/win32/direct2d/d2dfont.cpp
A return value of S_OK from `IDWriteFontCollection::FindFamilyName()` does not mean that a matching font family was found; the `index` or `exists` value need to be checked before calling `GetFontFamily()` or an `IndexOutOfRangeException` can be thrown (and caught) within the latter function, since `index` is set to `UINT_MAX` if no matching family was found.
https://learn.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritefontcollection-findfamilyname
Without this fix, log messages like the following are seen if font lookup fails:
```
Exception thrown at 0x00007FFC4FF1CF19 in VST3PluginTestHost.exe: Microsoft C++ exception: IndexOutOfRangeException at memory location 0x00000000001489E0.
Exception thrown at 0x00007FFC4FF1CF19 in VST3PluginTestHost.exe: Microsoft C++ exception: …
```
=> Fix IndexOutOfRangeException in d2dfont getFont()

vstgui/lib/platform/win32/direct2d/d2dbitmap.cpp
fix a bug that D2DBitmap::createHBitmap from CBitmap got a vertical mirror
=> fix a bug that D2DBitmap::createHBitmap from CBitmap got a vertical mirror

vstgui/lib/CMakeLists.txt, vstgui/lib/platform/mac/coregraphicsdevicecontext.mm, vstgui/lib/platform/win32/direct2d/d2dgraphicscontext.cpp
There's a new cmake option 'VSTGUI_TEXTRENDERING_LEGACY_INCONSISTENCY' which can be enabled to get the old behaviour.
This fixes #298
=> Apply bxjoscha's text rendering inconsistency fix

vstgui/lib/platform/linux/cairogradient.cpp, vstgui/lib/platform/linux/cairogradient.h, vstgui/lib/platform/linux/cairographicscontext.cpp
I followed this tutorial about gradients with cairo: https://zetcode.com/gfx/cairo/gradients/
I compared to Windows and with the same settings in the VSTGUI Live Editor I got identical looking results. Sometimes there is a "hickup": When moving around the view the radial gradient gets sticky and does not follow the view any longer. But when saving it "jumps" back into place.
Furthermore there is the ```originOffset```  argument of ```fillRadialGradient```. But I don't know what it is for. It is always (0,0) and I cannot make it change by any setting in VSTGUI Live Editor.
=> Implementation of the radial gradient with cairo for Linux.

vstgui/lib/platform/mac/cocoa/cocoahelpers.mm
Menu items configured with `setVirtualKey(VSTGUI::VirtualKey::Back)` were incorrectly showing the delete symbol instead.
This change makes menu items show the symbol that matches the backspace key on Mac keyboards;
=> Fix rendering of VirtualKey::Back in Cocoa menu items

vstgui/lib/crowcolumnview.cpp, vstgui/lib/crowcolumnview.h, vstgui/tests/unittest/lib/crowcolumnview_test.cpp, vstgui/tests/unittest/uidescription/uiviewcreator/crowcolumnviewcreator_test.cpp, vstgui/uidescription/viewcreator/rowcolumnviewcreator.cpp, vstgui/uidescription/viewcreator/rowcolumnviewcreator.h
Implementation of an Auto Layout like described on this website: https://medium.com/timeless/figma-updates-new-auto-layout-alignments-ec6cb134aea4
You can access the new layouts in the VSTGUI Live editor ```Row Column View Container: equal-size-layout``` (```equal-size-layout``` could be renamed as the new auto layout also allows different view sizes of children).
* auto layout is an extension of ```CRowColumnViews``` layout options
* new options ```top-left, top-center, top-right, middle-left, middle-center, middle-right, bottom-left, bottom-center, bottom-right``` integrate into the existing mechanism (the old ones are working as usual)
* ```Row Column View Container : spacing``` between views is maintained
* new unit tests for ```CRowColumView``` layout created
* existing …
=> Implementation of an Auto Layout for Row Column View Container

vstgui/lib/platform/win32/direct2d/d2dfont.cpp, vstgui/lib/platform/win32/direct2d/d2dfont.h, vstgui/lib/platform/win32/win32factory.cpp
=> initialize fonts on Windows when the resource base path is set
